name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Вкажіть версію Node.js, яка вам потрібна

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: https://conduit.realworld.how/ # Замініть на URL вашого додатка, якщо потрібно

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results # Шлях до результатів тестування, замініть на ваш фактичний шлях
